// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoLCJJRlnFlsbeVQE7WKGe3zGdI1S0Tn8',
    appId: '1:398622666633:web:d1bd9ff74275888ef7bb58',
    messagingSenderId: '398622666633',
    projectId: 'petcare-new',
    authDomain: 'petcare-new.firebaseapp.com',
    storageBucket: 'petcare-new.appspot.com',
    measurementId: 'G-E36LPFXPMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Oy0o6qqhTWBytIPzSx9Ze-D0M39v4IU',
    appId: '1:398622666633:android:948a98819a20cac2f7bb58',
    messagingSenderId: '398622666633',
    projectId: 'petcare-new',
    storageBucket: 'petcare-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDTwhVf4YEKIw0xINo6HtYFOMB2Mi6AYM',
    appId: '1:398622666633:ios:071f20df64407988f7bb58',
    messagingSenderId: '398622666633',
    projectId: 'petcare-new',
    storageBucket: 'petcare-new.appspot.com',
    iosBundleId: 'com.example.petcareNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDTwhVf4YEKIw0xINo6HtYFOMB2Mi6AYM',
    appId: '1:398622666633:ios:6590cdd1c2b62d9bf7bb58',
    messagingSenderId: '398622666633',
    projectId: 'petcare-new',
    storageBucket: 'petcare-new.appspot.com',
    iosBundleId: 'com.example.petcareNew.RunnerTests',
  );
}
